# Generated by Django 5.2.8 on 2026-03-05 14:47
from django.db import migrations


def create_notification_types(apps, schema_editor):
    NotificationType = apps.get_model('notifications', 'NotificationType')
    
    notification_types = [
        {
            'name': 'Order Confirmation',
            'code': 'order_confirmation',
            'description': 'Sent when an order is placed',
            'email_template': 'order_confirmation',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
        {
            'name': 'Payment Confirmation',
            'code': 'payment_confirmation',
            'description': 'Sent when payment is confirmed',
            'email_template': 'payment_confirmation',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
        {
            'name': 'Shipping Update',
            'code': 'shipping_update',
            'description': 'Sent when order ships',
            'email_template': 'shipping_update',
            'email_enabled': True,
            'sms_enabled': True,
            'push_enabled': False,
        },
        {
            'name': 'Order Delivered',
            'code': 'order_delivered',
            'description': 'Sent when order is delivered',
            'email_template': 'order_delivered',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
        {
            'name': 'Order Cancelled',
            'code': 'order_cancelled',
            'description': 'Sent when order is cancelled',
            'email_template': 'order_cancelled',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
        {
            'name': 'Password Reset',
            'code': 'password_reset',
            'description': 'Sent for password reset requests',
            'email_template': 'password_reset',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
        {
            'name': 'Welcome Email',
            'code': 'welcome',
            'description': 'Sent to new users',
            'email_template': 'welcome_email',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
        {
            'name': 'Promotional',
            'code': 'promotional',
            'description': 'Marketing and promotional emails',
            'email_template': 'promotional',
            'email_enabled': True,
            'sms_enabled': True,
            'push_enabled': True,
        },
        {
            'name': 'Newsletter',
            'code': 'newsletter',
            'description': 'Newsletter updates',
            'email_template': 'newsletter',
            'email_enabled': True,
            'sms_enabled': False,
            'push_enabled': False,
        },
    ]
    
    for nt in notification_types:
        NotificationType.objects.create(**nt)


def reverse_func(apps, schema_editor):
    NotificationType = apps.get_model('notifications', 'NotificationType')
    NotificationType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),  # This depends on the first migration
    ]

    operations = [
        migrations.RunPython(create_notification_types, reverse_func),
    ]