# Generated by Django 5.2.8 on 2026-03-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('notifications', '0003_add_default_notification_types'),
    ]

    operations = [
    ]
