# Generated by Django 5.2.8 on 2026-03-05 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MastercardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_encrypted', models.TextField()),
                ('cardholder_name', models.CharField(max_length=255)),
                ('expiry_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2050)])),
                ('last_four', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('mastercard', 'Mastercard'), ('mastercard_standard', 'Mastercard Standard'), ('mastercard_gold', 'Mastercard Gold'), ('mastercard_platinum', 'Mastercard Platinum'), ('mastercard_world', 'Mastercard World'), ('mastercard_world_elite', 'Mastercard World Elite'), ('debit_mastercard', 'Debit Mastercard'), ('mastercard_prepaid', 'Mastercard Prepaid')], default='mastercard', max_length=30)),
                ('mastercard_transaction_id', models.CharField(blank=True, max_length=100)),
                ('verification_value', models.CharField(max_length=100)),
                ('is_3d_secure_enrolled', models.BooleanField(default=False)),
                ('secure_code_id', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mastercard Card',
                'verbose_name_plural': 'Mastercard Cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MastercardPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('mastercard_transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('authorize', 'Authorize Only'), ('capture', 'Capture'), ('refund', 'Refund'), ('void', 'Void'), ('verify', 'Verification')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('settled', 'Settled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('declined', 'Declined'), ('chargeback', 'Chargeback')], default='initiated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham')], default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=3)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=30)),
                ('mastercard_request_id', models.CharField(blank=True, max_length=100)),
                ('mastercard_response_code', models.CharField(blank=True, max_length=10)),
                ('mastercard_response_reason', models.TextField(blank=True)),
                ('auth_code', models.CharField(blank=True, max_length=50)),
                ('retrieval_reference_number', models.CharField(blank=True, max_length=50)),
                ('is_3d_secure', models.BooleanField(default=False)),
                ('three_d_secure_status', models.CharField(blank=True, max_length=50)),
                ('three_d_secure_eci', models.CharField(blank=True, max_length=2)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('response_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('fraud_check_passed', models.BooleanField(default=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mastercard Transaction',
                'verbose_name_plural': 'Mastercard Transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('items', models.JSONField(default=list)),
                ('item_count', models.IntegerField(default=0)),
                ('shipping_address', models.JSONField()),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_method', models.CharField(choices=[('standard', 'Standard Shipping (3-5 days)'), ('express', 'Express Shipping (1-2 days)'), ('overnight', 'Overnight Shipping'), ('pickup', 'Store Pickup')], default='standard', max_length=20)),
                ('shipping_carrier', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('payment_processing', 'Payment Processing'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('chargeback', 'Chargeback')], default='pending', max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('mastercard', 'Mastercard'), ('visa', 'Visa'), ('amex', 'American Express'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
