# Generated by Django 5.2.8 on 2026-03-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='mastercardcard',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.useraddress'),
        ),
        migrations.AddField(
            model_name='mastercardcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastercardpaymenttransaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.mastercardcard'),
        ),
        migrations.AddField(
            model_name='mastercardpaymenttransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.mastercardpaymenttransaction'),
        ),
        migrations.AddField(
            model_name='mastercardpaymenttransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastercard_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.mastercardpaymenttransaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastercardpaymenttransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastercard_payments', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'session_key')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercardpaymenttransaction',
            index=models.Index(fields=['transaction_id'], name='orders_mast_transac_dc395a_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercardpaymenttransaction',
            index=models.Index(fields=['mastercard_transaction_id'], name='orders_mast_masterc_f30bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercardpaymenttransaction',
            index=models.Index(fields=['order'], name='orders_mast_order_i_1f8622_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercardpaymenttransaction',
            index=models.Index(fields=['user'], name='orders_mast_user_id_4d2a97_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercardpaymenttransaction',
            index=models.Index(fields=['status'], name='orders_mast_status_dbdf6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercardpaymenttransaction',
            index=models.Index(fields=['-initiated_at'], name='orders_mast_initiat_f36247_idx'),
        ),
    ]
